version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_URI=$REPOSITORY_URI/xds-gatekeeper
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker build -t $IMAGE_URI:latest .
      - docker tag $IMAGE_URI:latest $IMAGE_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $IMAGE_URI:latest
      - docker push $IMAGE_URI:$IMAGE_TAG
      - printf '[{"name":"xds-gatekeeper","imageUri":"%s"}]' $IMAGE_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
