apiVersion: v1
kind: Service
metadata:
  labels:
    app: gatekeeper
  name: gatekeeper
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4180
  selector:
    app: gatekeeper
